### ISSUE TITLE
helm repo update

### ISSUE THREAD

**Issue by webmutation** [xebialabs-community/xld-helm-plugin#8]
If the host of the helm does not have the helm repo updated it will fail existing helm charts. To make sure that it is updated to the latest version it is ideal to add this command before doing the install. Otherwise we have the following error

`Error: chart "name" matching 1.1.5 not found in repo_helm index. (try 'helm repo update'): no chart version found for name-1.1.5`

**Comment by bmoussaud** [comment]
It makes sense. It's possible to add an optional rule that will trigger the 'helm repo update' the command before running the helm command.
